# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group_permissions',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_permission',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_groups',
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'django_content_type',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('domid', models.IntegerField(primary_key=True, serialize=False)),
                ('domainname', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'domains',
            },
        ),
        migrations.CreateModel(
            name='Profcontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'profcontact',
            },
        ),
        migrations.CreateModel(
            name='Profemail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'profemail',
            },
        ),
        migrations.CreateModel(
            name='Profidea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newprojid', models.IntegerField()),
                ('idea', models.TextField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'profidea',
            },
        ),
        migrations.CreateModel(
            name='Profinfo',
            fields=[
                ('profid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('passwd', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'profinfo',
            },
        ),
        migrations.CreateModel(
            name='Projdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'projdom',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('dateofreg', models.DateField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('complete', models.NullBooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Projfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileid', models.IntegerField()),
                ('fpath', models.TextField(blank=True, null=True)),
                ('adate', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'projfiles',
            },
        ),
        migrations.CreateModel(
            name='Projprof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'projprof',
            },
        ),
        migrations.CreateModel(
            name='Projprofcom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentid', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'projprofcom',
            },
        ),
        migrations.CreateModel(
            name='Studcontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'studcontact',
            },
        ),
        migrations.CreateModel(
            name='Studemail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'studemail',
            },
        ),
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('passwd', models.TextField(blank=True, null=True)),
                ('sem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'studentinfo',
            },
        ),
        migrations.CreateModel(
            name='Studprojgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'studprojgrade',
            },
        ),
    ]
