# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('se1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studcontact',
            options={'managed': True},
        ),
    ]
