# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('se1', '0002_auto_20160306_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studcontact',
            options={'managed': False},
        ),
    ]
